CS2_SKIN_CATALOG = [
    {
        "name": "AK-47 | Redline (Field-Tested)",
        "rarity": "Classified",
        "category": "Rifle",
        "thesis": "High trading velocity and long-term demand as a staple AK skin.",
    },
    {
        "name": "AK-47 | Asiimov (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Strong brand recognition in the Asiimov line with recurring buyer interest.",
    },
    {
        "name": "AK-47 | Vulcan (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Collector-friendly legacy skin with resilient liquidity across cycles.",
    },
    {
        "name": "AK-47 | The Empress (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Premium visual tier with active marketplace turnover.",
    },
    {
        "name": "M4A1-S | Printstream (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Consistent demand from both players and inventory investors.",
    },
    {
        "name": "M4A1-S | Player Two (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Popular M4A1-S option with broad market audience.",
    },
    {
        "name": "M4A4 | Neo-Noir (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Established art-driven skin with stable medium-high liquidity.",
    },
    {
        "name": "M4A4 | The Emperor (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Strong long-term interest from themed loadout buyers.",
    },
    {
        "name": "AWP | Asiimov (Battle-Scarred)",
        "rarity": "Covert",
        "category": "Sniper",
        "thesis": "One of the most recognized AWP skins with frequent trades.",
    },
    {
        "name": "AWP | Hyper Beast (Field-Tested)",
        "rarity": "Covert",
        "category": "Sniper",
        "thesis": "High visibility skin with recurring volatility opportunities.",
    },
    {
        "name": "AWP | Neo-Noir (Field-Tested)",
        "rarity": "Covert",
        "category": "Sniper",
        "thesis": "Modern AWP pick with robust buyer frequency.",
    },
    {
        "name": "AWP | Redline (Field-Tested)",
        "rarity": "Classified",
        "category": "Sniper",
        "thesis": "Affordable AWP classic with deep listing depth.",
    },
    {
        "name": "Desert Eagle | Blaze (Factory New)",
        "rarity": "Restricted",
        "category": "Pistol",
        "thesis": "High-value pistol icon with strong prestige-driven demand.",
    },
    {
        "name": "Desert Eagle | Printstream (Field-Tested)",
        "rarity": "Covert",
        "category": "Pistol",
        "thesis": "Premium finish that frequently appears in active inventories.",
    },
    {
        "name": "Glock-18 | Fade (Factory New)",
        "rarity": "Classified",
        "category": "Pistol",
        "thesis": "Collector-preferred fade pattern supporting long horizon demand.",
    },
    {
        "name": "USP-S | Kill Confirmed (Minimal Wear)",
        "rarity": "Covert",
        "category": "Pistol",
        "thesis": "Flagship USP skin with broad appeal and consistent turnover.",
    },
    {
        "name": "USP-S | Neo-Noir (Field-Tested)",
        "rarity": "Covert",
        "category": "Pistol",
        "thesis": "Popular skin line with repeat retail flow.",
    },
    {
        "name": "P250 | Asiimov (Field-Tested)",
        "rarity": "Classified",
        "category": "Pistol",
        "thesis": "Affordable entry-tier Asiimov with steady buyer base.",
    },
    {
        "name": "Five-SeveN | Hyper Beast (Minimal Wear)",
        "rarity": "Covert",
        "category": "Pistol",
        "thesis": "Active mid-cap skin suited for momentum strategies.",
    },
    {
        "name": "MAC-10 | Neon Rider (Field-Tested)",
        "rarity": "Covert",
        "category": "SMG",
        "thesis": "High circulation SMG with recurring short-term trend bursts.",
    },
    {
        "name": "MP9 | Starlight Protector (Field-Tested)",
        "rarity": "Covert",
        "category": "SMG",
        "thesis": "Recent-era sought skin with healthy listing activity.",
    },
    {
        "name": "P90 | Death by Kitty (Factory New)",
        "rarity": "Classified",
        "category": "SMG",
        "thesis": "Nostalgic collector skin with periodic demand spikes.",
    },
    {
        "name": "FAMAS | Commemoration (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Low-base niche rifle with occasional outsized moves.",
    },
    {
        "name": "Galil AR | Chatterbox (Field-Tested)",
        "rarity": "Covert",
        "category": "Rifle",
        "thesis": "Legacy Galil favorite offering cyclical repricing potential.",
    },
    {
        "name": "SSG 08 | Dragonfire (Field-Tested)",
        "rarity": "Covert",
        "category": "Sniper",
        "thesis": "Recognizable scout skin with medium liquidity and trendability.",
    },
]
